### PR TITLE
Creating a PR request for my Soul Fitness v1.0

### PR DESCRIPTION
**Pull request by sdhamani**
Hello Everyone,

This is version one of my e-commerce application Soul-Fitness.

Website is deployed on - https://soul-fitness.netlify.app/

Tech Stach - 
1. Backend - We used Express JS for framework, node for runtime environment, Mongo DB for database, and jwt for authentication.
2. Frontend - We used react JS for JS library, CSS for styling, and context API for state management, and react-router v-6 for routing.

Features - 
1. Responsive Landing page with featured products.
2. Features including add to cart, add to wishlist and update cart and wishlist integrated with real-time backend interaction.
3. Login and sign up for real-time authentication fully integrated with backend and database and jwt for tokens.
4. Checkout page with the complete list of cart items along with the total price and policies.

Please go through the site and I would be happy to know your feedback as that would help me to become a good developer.

Thanks & Regards,
Sagar Dhamani

### CODE REVIEW

**Comment by OmkarArora** [comment]
I went through the app and the code, the design looks good. I found some things you might want to change - 

1. Remove all the console logs, many objects are getting logged currently
image

2.  data/product.js file is completely commented and you are exporting an empty array. You could remove this file completely.

3.  Remove the setupTests.js and reportWebVitals.js files if you are not actually using them yet.

4. There is only one line in App.css, you can move that to index.css directly and then remove App.css.

Rest of the code looks great. The file and folder structure, naming schemes etc. all look fine.

**Comment by sdhamani** [comment]
> I went through the app and the code, the design looks good. I found some things you might want to change -
> 
> 1. Remove all the console logs, many objects are getting logged currently
>    image
> 2. data/product.js file is completely commented and you are exporting an empty array. You could remove this file completely.
> 3. Remove the setupTests.js and reportWebVitals.js files if you are not actually using them yet.
> 4. There is only one line in App.css, you can move that to index.css directly and then remove App.css.
> 
> Rest of the code looks great. The file and folder structure, naming schemes etc. all look fine.

Hi Omkar, 
Thank you for reviewing my PR.
I have made the above changes. Can you please check ?

**Review by OmkarArora — APPROVED** [review]
The app looks good to go after the changes.

**Comment by Akshaay9** [comment]
Hey sagar, Nice work, Really loved your home page and skeleton loaders, here are the few changes that i think makes your website looks even better

1. Images present in product list feels little stretched out, so you could add these extra css
`.card-image-ecom {
wid:100%,
object fit:contains
}`
2. In cart page, when the cart QTY becomes 1, and when user clicks on `-` button, instead of making it disable, just remove the product from cart same way as delete item from cart

Other than these, everything looks fine
Great Job.

**Comment by ishanjirety** [comment]
Hi Sagar, the code & UI looks good although there are some issues 

UI
- whenever these filters are selected products keep loading.
 image

- Equipment tab keeps loading 
- Footer is not fixed to the bottom 
- Add 404 page

Code 
- Clean boilerplate code and remove unused files 
- Use index.js in context to export files from folder to avoid these 
image

**Comment by sdhamani** [comment]
> Hi Sagar, the code & UI looks good although there are some issues
> 
> UI
> 
> * whenever these filters are selected products keep loading.
>   image
> * Equipment tab keeps loading
> * Footer is not fixed to the bottom
> * Add 404 page
> 
> Code
> 
> * Clean boilerplate code and remove unused files
> * Use index.js in context to export files from folder to avoid these
>   image

Hi Ishan,
Thanks a lot for reviewing my code.

I have made all the changes and they are working fine.

Thanks & Regards,
Sagar Dhamani

**Pull request merged**
